# Generated by Django 4.1.7 on 2023-02-17 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_catagory_post_catagories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='catagories',
            new_name='categories',
        ),
    ]
