# Generated by Django 4.1.7 on 2023-03-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_post_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='breaking_news',
            field=models.BooleanField(default=False),
        ),
    ]
