# Generated by Django 4.1.7 on 2023-03-03 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_post_breaking_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='breaking_news',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
